spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/company?useUnicode=true&CharacterEncoding=utf8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:static/mapper/*Mapper.xml
  type-aliases-package: com.thhy.fixedassets.domain

logging:
  level:
    com.thhy.fixedassets.dao: debug